# You can use a Docker image from Docker Hub or your own container
# registry for your build environment.
image: golang:1.8-alpine

pipelines:
  default:
    - step:
        script:
          - apk add --no-cache git make 
          - make golang